### ISSUE TITLE
Introduce `mass`

### ISSUE THREAD

**Issue by cortner** [JuliaMolSim/AtomsBase.jl#100]
I think the default mass of a particle should be `mass` and not `atomic_mass`. 

First, this does not create any ambiguities:   The prefix `atomic_` is to emphasize it is the mass of an atom. If the particle of which we are getting the mass is an atom then that information is already encoded in the type of the particle object. In other words, `mass(x::Atom)` already encodes all the information, whereas `atomic_mass(x::Atom)` duplicates it. 

Secondly, it will generalize the terminology to other particles that are not necessarily atoms. 

One could introduce `mass` side by side with `atomic_mass` or it could entirely replace `atomic_mass`.

**Comment by mfherbst** [comment]
Personally I don't care so much about the name.

**Comment by cortner** [comment]
maybe to be part of the next breaking version discussion
