### ISSUE TITLE
`position` conflicts with `Base.position`

### ISSUE THREAD

**Issue by rashidrafeek** [JuliaMolSim/AtomsBase.jl#18]
I am not sure this was known when `get_position` was changed to `position` in #4. But having an export conflicting with Base doesn't seem like a good idea. 
```julia
julia> using AtomsBase

julia> position
WARNING: both AtomsBase and Base export "position"; uses of it in module Main must be qualified
ERROR: UndefVarError: position not defined
```
This means that whenever `position` needs to be called , it would need to be written as `AtomsBase.position` unless we add a line `using AtomsBase: position`

It seems that exporting the name in Base was a mistake, but it won't be changed until julia 2.0 (See https://github.com/JuliaLang/julia/issues/33799)

**Comment by thchr** [comment]
I ran into this as well in an related context and came upon this issue.

One alternative to changing the name is to just extend `Base.position` for your own types rather defining `AtomsBase.position`. It seems that such an approach has been used [relatively widely in the wild](https://juliahub.com/ui/Search?q=Base.position&type=code) (also for non-stream types).

**Comment by mfherbst** [comment]
Yes and no. I think it makes only sense to extend base functions if the idea / action of the base and the custom function are related. Otherwise it's a potentially confusing misuse of the Base function name in my opinion.

In this case (position of atoms list versus position in a stream) seems very different.

**Comment by thazhemadam** [comment]
> Yes and no. I think it makes only sense to extend base functions if the idea / action of the base and the custom function are related. Otherwise it's a potentially confusing misuse of the Base function name in my opinion.
>
> In this case (position of atoms list versus position in a stream) seems very different.

Thanks to multiple dispatch, what a method does (and how it does it ofc) is essentially defined by the type(s) a method acts on. `Base.position` returns the position in a stream _while acting upon_ an IO object (`IOStream`). What matters more is that the method name makes semantic sense in the context of the types it works on and the rest is a little more flexible, as I've come to learn.
I'm not familiar enough with the API to be opinionated about this so I'll leave it to you experts, but I just wanted to point that out 😄

**Comment by thchr** [comment]
I generally agree with your sentiment @mfherbst; but in this case where it seems everyone (JuliaLang/julia#33799) agrees that even having `Base.position` was a mistake, whether on streams or not, I think it can make sense to bend the rules.
(but I don't have skin in the game here - so it's just a general opinion on this specific issue).

**Comment by mfherbst** [comment]
Yeah. I had another look at this and I agree. This one is a bit of a special case, where it's sort of ok. In fact plenty of other codes have sort of already established "our" interpretation of the `position` function, so our current consensus is to just import `position` from Base and provide a new method for it.
