### ISSUE TITLE
Should slicing work? If so, what should it do?

### ISSUE THREAD

**Issue by rkurchin** [JuliaMolSim/AtomsBase.jl#29]
Currently, you can only use single indices. Intuitively, I would say slicing should return a new system with the same bounding box, boundary conditions, etc. but only containing the sliced indices. However, one could also imagine it returning a list of the actual particle objects referenced by the indices...also, either of these becomes a bit fraught in the case of a lattice with Cartesian indexing because the bounding box is more "intimately" connected to the specific particles/sites...so maybe not supporting slicing at the top level is fine?

**Comment by jgreener64** [comment]
I would lean towards it returning a list of the actual particle objects referenced by the indices; this means it would be possible to define a default at the top level, which I think is difficult in the first case.

If we added
```julia
Base.getindex(s::AbstractSystem, r::Union{UnitRange, AbstractArray}) = getindex.((s,), r)
```
that would provide this slicing behaviour, e.g. for the test example
```julia
julia> aos[1:2]
2-element Vector{StaticAtom{3, Quantity{Float64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}}}:
 StaticAtom: C
 StaticAtom: C

julia> aos[[1, 2]]
2-element Vector{StaticAtom{3, Quantity{Float64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}}}:
 StaticAtom: C
 StaticAtom: C
```

I agree that non-standard indexing will complicate this a bit but the array case above would still work with an array of more complex indices.

Agree it's borderline whether it is worth supporting at the top level though.

**Comment by Kolaru** [comment]
I agree that slicing should return a vector of particle object. I think that this kind of advanced indexing is the natural way of querying the particles.

On simple example is getting all hydrogen atoms in the system. It could look something like the following
```julia
hydrogens = system[element.(system) .== :H]
```
(provided `element` is defined for the particle in the system). This requires indexing with a boolean array rather than slicing, but I believe it follows the same global idea.

**Comment by mfherbst** [comment]
With @rashidrafeek's PR the discussed features should work now. Closing this for now.
