### ISSUE TITLE
Should `get_` be removed from the getter functions

### ISSUE THREAD

**Issue by jgreener64** [JuliaMolSim/AtomsBase.jl#4]
At the minute the getter functions such as `get_position`, `get_box` etc. are preceded by `get_`.

I can see the advantage of keeping common variable names free, but I lean towards the Julia convention of not using `get_` (and adding `!` for any corresponding setters).

Do others have opinions on this?

**Comment by Gregstrq** [comment]
I think it is indeed bothersome to always right these "get_". So I lean towards stripping these "get_" with the only exception of `getindex` which is the base function.
