### ISSUE TITLE
`AbstractSystem` as a subtype of `AbstractArray`

### ISSUE THREAD

**Issue by Gregstrq** [JuliaMolSim/AtomsBase.jl#6]
Right now, `AbstractSystem` is defined as a subtype of `AbstractVector`. In case of a static `D`-dimensional lattice it is more convenient to use cartesian indices instead of linear indices, so this subtyping does not make much sense in this particular case.

Instead, `AbstractSystem` could subtype `AbstractArray` ( or not subtype anything).
In either case, we keep the functions `Base.getindex` and `Base.size`. I also propose to add `Base.length` to the list of interface functions because `Base.size` and `Base.length` have different meaning in the context of multidimensional arrays.

**Comment by rkurchin** [comment]
I think this modification makes sense. Allows the vector case but also the Cartesian indexing when that makes more sense. I can't see a downside...

**Comment by mfherbst** [comment]
I agree. Whether it's an array or a vector does not make much of a difference for our use case. If it helps your use case then I think we should make this change.
