### ISSUE TITLE
Element can't be found when using String for AtomID

### ISSUE THREAD

**Issue by louisponet** [JuliaMolSim/AtomsBase.jl#71]
https://github.com/JuliaMolSim/AtomsBase.jl/blob/652f9166fc3c1c8c04f76b4c99e28aa31db3002a/src/interface.jl#L91

MWE:
```
Atom("Si", zeros(3)u"\AA")
```

**Comment by jgreener64** [comment]
Slight preference for 1, then 3.

**Comment by mfherbst** [comment]
I made a proposal in #72. Let me know what you think.
